version: '3.8'

services:
  apache-backend:
    build: ./apache
    container_name: apache_nimbus_server
    networks:
      - nimbus-red

  nginx-proxy:
    build: ./nginx
    container_name: nginx_nimbus_proxy
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - apache-backend
    networks:
      - nimbus-red

networks:
  nimbus-red:
    driver: bridge
    